const arrays = {
	newProductMain: {
		options: {
			SIType: ['UPC', 'EAN', 'ISBN'],
			Battery: ['NO', 'YES'],
			ApplicableDangerous: [
				'GHS',
				'Storage',
				'Waste',
				'Not Applicable',
				'Transportation',
				'Other',
				'Unknown',
			],
			VariationType: [
				'Size',
				'Color',
				'number_of_items',
				'LineSize',
				'SizeColor',
				'color - size',
				'material',
				'MaximumExpandableSize',
				'PaperSize',
				'SizeName',
				'SizeName - ColorName',
			],
		},
		descriptionField: {
			labels: [
				'Title',
				'Brand',
				'Description',
				'Bullet 1',
				'Bullet 2',
				'Bullet 3',
				'Bullet 4',
				'Bullet 5',
				'Manufacturer',
				'Search terms',
			],
			height: ['5', '5', '20', '13', '13', '13', '13', '13', '5', '10'],
			max: [200, 50, 2000, 999, 999, 999, 999, 999, 50, 249],
			names: [
				'title',
				'brand',
				'description',
				'bullet_1',
				'bullet_2',
				'bullet_3',
				'bullet_4',
				'bullet_5',
				'manufacturer',
				'search_terms',
			],
		},
		photoField: {
			photoType: {
				options: [
					'Main',
					'Swatch',
					'BKLB',
					'PT1',
					'PT2',
					'PT3',
					'PT4',
					'PT5',
					'PT6',
					'PT7',
					'PT8',
					'Search',
					'PM01',
					'MainOfferImage',
					'OfferImage1',
					'OfferImage2',
					'OfferImage3',
					'OfferImage4',
					'OfferImage5',
				],
			},
		},
		sizesField: {
			labels: [
				'Item weight',
				'Package weight',
				'Package width',
				'Package length',
				'Package height',
			],
			types: ['weight', 'weight', 'size', 'size', 'size'],
			options: {
				size: ['FT', 'IN', 'CM', 'MM', 'M'],
				weight: ['LB', 'OZ', 'KG', 'GR'],
			},
			names_size: [
				'item_weight',
				'package_weight',
				'package_width',
				'package_length',
				'package_height',
			],
			names_units: [
				'item_weight_mu',
				'package_weight_mu',
				'package_width_mu',
				'package_length_mu',
				'package_height_mu',
			],
		},
	},
	productList: {
		header: {
			values: ['SKU', 'Title'],
		},
	},
	createListing: {
		productList: {
			header: {
				values: ['SKU', 'Title'],
			},
		},
	},
}

export default arrays
