const arrays = {
	newProductMain: {
		options: {
			SIType: ['UPC', 'EAN', 'ISBN'],
			Battery: ['NO', 'YES'],
			ApplicableDangerous: [
				'GHS',
				'Storage',
				'Waste',
				'Not Applicable',
				'Transportation',
				'Other',
				'Unknown',
			],
			VariationType: [
				'Size',
				'Color',
				'number_of_items',
				'LineSize',
				'SizeColor',
				'color - size',
				'material',
				'MaximumExpandableSize',
				'PaperSize',
				'SizeName',
				'SizeName - ColorName',
			],
		},
		descriptionField: {
			labels: [
				'Title',
				'Brand',
				'Description',
				'Bullet 1',
				'Bullet 2',
				'Bullet 3',
				'Bullet 4',
				'Bullet 5',
				'Manufacturer',
			],
			height: ['5', '5', '20', '13', '13', '13', '13', '5'],
			max: ['200', '50', '2000', '300', '300', '300', '300', '300', '50'],
			names: [
				'title',
				'brand',
				'description',
				'bullet_1',
				'bullet_2',
				'bullet_3',
				'bullet_4',
				'bullet_5',
				'manufacturer',
			],
		},
		photoField: {
			photoType: {
				options: [
					'Main',
					'Swatch',
					'BKLB',
					'PT1',
					'PT2',
					'PT3',
					'PT4',
					'PT5',
					'PT6',
					'PT7',
					'PT8',
					'Search',
					'PM01',
					'MainOfferImage',
					'OfferImage1',
					'OfferImage2',
					'OfferImage3',
					'OfferImage4',
					'OfferImage5',
				],
			},
		},
		sizesField: {
			labels: [
				'Item weight',
				'Package weight',
				'Package width',
				'Package length',
				'Package height',
			],
			types: ['weight', 'weight', 'size', 'size', 'size'],
			options: {
				size: ['FT', 'IN', 'CM', 'MM', 'M'],
				weight: ['LB', 'OZ', 'KG', 'GR'],
			},
		},
	},
}

export default arrays
